name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Get tools
      run: sudo apt install nasm bcc gcc bin86 bochs bochs-x make
    - name: Building
      run: make all
